[MAIN]
;Version
;{
;    auto,
;    GTA_3_1_0,
;    GTA_3_1_1,
;    GTA_3_Steam
;}
Version=auto

; List of vehicle model IDs that are big. Having this list is absolutely necessary, otherwise it will be impossible to break their windshields in most cases.
;example1 - BigVehicles=122,119,90,131
;example2 - BigVehicles=
;example3 - BigVehicles=122
BigVehicles=93,97,98,104,106,121,123,132,133,138,145,146

; List of vehicle model IDs that are immune to windshields break.
;example1 - BannedVehicles=122,119,90,131
;example2 - BannedVehicles=
;example3 - BannedVehicles=122
BannedVehicles=

; Enables glass shatters effect.
bGlassFx=True

; Enables glass shatters effect from Vice City, otherwise GTA 3 effect will be used.
bViceCityGlassFx=True

; Fixes glass shatters effect bug that's only present in GTA 3. Without this fix, the glass polygons will look stretched and weird. 
bFixLongDebrisBugByRockstar=True

; Allows you to break a car glass with a shotgun. Not a Vice City feature, but it's nice to have.
bBreakGlassWithShotgun=True

; Ped die animation ID.
nAnim1=37

; Ped leave car animation ID
nAnim2=173

; Enables CLEO integration. The plugin uses this to add the opcode that is required for the modified main.scm.
bAddOpcodesForCleo=True

; Opcode/Script command IDs.
[OPCODES]
SET_CHAR_CAN_BE_SHOT_IN_VEHICLE=0x54A